### ISSUE TITLE
x64 plugin 

### ISSUE THREAD

**Issue by Reel-Deal** [299792458m/UnsharpHQmod#1]
Hi,

Thank you for the updates on this plugin. If possible can you release a x64 plugin?

**Comment by 299792458m** [comment]
Sorry, I've gone somewhere

added the release bin file. (but AVX2 only because I don't have SSE2 only CPUs...)

**Comment by 299792458m** [comment]
recompiled without compiler's AVX2 opt (maybe almost same)

**Comment by Reel-Deal** [comment]
Hi, thank you for uploading an x64 build. However, Asd-g updated this filter to pass frame properties in AviSynth+. Maybe you can incorporate the changes: [UnsharpHQmod_dacebe3_fp.7z](https://drive.google.com/file/d/13jrDXS12jYWaveJzLtD-AmYiE3dKE3n6/view?usp=sharing)
